/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../android_develop/sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_storn_freechat_jni_XMPPCommon */

#ifndef _Included_com_storn_freechat_jni_FreeChatCommon
#define _Included_com_storn_freechat_jni_FreeChatCommon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_storn_freechat_jni_FreeChatCommon
 * Method:    getXMPPHost
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_storn_freechat_jni_FreeChatCommon_getXMPPHost
  (JNIEnv *, jclass);

/*
 * Class:     com_storn_freechat_jni_FreeChatCommon
 * Method:    getXMPPServerName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_storn_freechat_jni_FreeChatCommon_getXMPPServerName
  (JNIEnv *, jclass);

/*
 * Class:     com_storn_freechat_jni_FreeChatCommon
 * Method:    getXMPPPort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_storn_freechat_jni_FreeChatCommon_getXMPPPort
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
